# Generated by Django 5.0.1 on 2024-07-07 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_remove_tweet_nickname_tweet_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 7, 37, 51, 433220, tzinfo=datetime.timezone.utc)),
        ),
    ]
